[build-system]
requires = ["setuptools", "wheel"]
build-backend = "setuptools.build_meta"

# [project]
[tool.poetry]
name = "pytibrv"
version = "0.1.0"
description = "TIBRV Python bindings"
authors = ["Arien Chen <arienchen@example.com>"]
license = "MIT"

[tool.poetry.dependencies]
python = ">=3.6"

